"""empty message

Revision ID: ac4a72279075
Revises: f592a8becfb1
Create Date: 2023-05-19 20:31:49.919270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4a72279075'
down_revision = 'f592a8becfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('cod_producto',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('cod_producto',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
