"""empty message

Revision ID: f477819f53f8
Revises: 
Create Date: 2023-05-20 23:30:22.064360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f477819f53f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_table('tipo_pago',
    sa.Column('id_tipo_pago', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_pago')
    )
    op.create_table('comuna',
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['region.id_region'], ),
    sa.PrimaryKeyConstraint('id_comuna')
    )
    op.create_table('producto',
    sa.Column('cod_producto', sa.String(length=250), nullable=False),
    sa.Column('serie_producto', sa.String(length=250), nullable=False),
    sa.Column('marca', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.LargeBinary(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('precio_dolar', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('cod_producto')
    )
    op.create_table('usuario',
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=250), nullable=False),
    sa.Column('apellidos', sa.String(length=250), nullable=False),
    sa.Column('domicilio', sa.String(length=250), nullable=True),
    sa.Column('id_comuna', sa.Integer(), nullable=True),
    sa.Column('fono', sa.Integer(), nullable=True),
    sa.Column('nombre_usuario', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['comuna.id_comuna'], ),
    sa.PrimaryKeyConstraint('rut')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('id_tipo_pago', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_pago'], ['tipo_pago.id_tipo_pago'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.rut'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalle_venta',
    sa.Column('id_detalle_venta', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('cod_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_producto'], ['producto.cod_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle_venta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_venta')
    op.drop_table('venta')
    op.drop_table('usuario')
    op.drop_table('producto')
    op.drop_table('comuna')
    op.drop_table('tipo_pago')
    op.drop_table('region')
    op.drop_table('categoria')
    # ### end Alembic commands ###
